//! x86_64 の Linux の ABI（システムコールの番号・引数のレジスタ・構造体の配置・errno。`ADR-0071` の
//! 決定 1 の 2 で、共通の側から移す）。

mod errno;

pub use errno::{
    E2BIG, EACCES, EADDRINUSE, EAFNOSUPPORT, EAGAIN, EBADF, EBUSY, ECHILD, ECONNREFUSED, EEXIST,
    EFAULT, EINVAL, EIO, EISCONN, EISDIR, EMFILE, EMSGSIZE, ENAMETOOLONG, ENOBUFS, ENODEV, ENOENT,
    ENOMEM, ENOSPC, ENOSYS, ENOTCONN, ENOTDIR, ENOTEMPTY, ENOTSOCK, ENOTTY, EPIPE, EPROTONOSUPPORT,
    EROFS, ESPIPE,
};
