//! x86_64 の Linux の ABI（システムコールの番号・引数のレジスタ・構造体の配置・errno。`ADR-0071` の
//! 決定 1 の 2 で、共通の側から移す）。

mod errno;

pub use errno::{
    E2BIG, EACCES, EADDRINUSE, EAFNOSUPPORT, EAGAIN, EBADF, EBUSY, ECHILD, ECONNREFUSED, EEXIST,
    EFAULT, EINVAL, EIO, EISCONN, EISDIR, EMFILE, EMSGSIZE, ENAMETOOLONG, ENOBUFS, ENODEV, ENOENT,
    ENOMEM, ENOSPC, ENOSYS, ENOTCONN, ENOTDIR, ENOTEMPTY, ENOTSOCK, ENOTTY, EPIPE, EPROTONOSUPPORT,
    EROFS, ESPIPE,
};

mod layout;

pub use layout::{
    DIRENT64_ALIGN, DIRENT64_HEADER_LEN, DRM_CLIP_RECT_LEN, FB_FIX_SCREENINFO_LEN,
    FB_VAR_SCREENINFO_LEN, POLLFD_LEN, SOCKADDR_UN_LEN, STAT_BLOCKS, STAT_INO, STAT_LEN, STAT_MODE,
    STAT_NLINK, STAT_SIZE, TIMESPEC_LEN, TIMESPEC_NSEC, WINSIZE_LEN,
};

mod values;

pub use values::{
    AF_UNIX, CLOCK_MONOTONIC, DT_DIR, DT_REG, DT_UNKNOWN, FBIOGET_FSCREENINFO, FBIOGET_VSCREENINFO,
    FB_TYPE_PACKED_PIXELS, FB_VISUAL_TRUECOLOR, O_ACCMODE, O_CREAT, O_RDONLY, O_TRUNC, O_WRONLY,
    POLLIN, PROT_WRITE, SCM_RIGHTS, SEEK_SET, SOCK_STREAM, SOL_SOCKET, TIOCGWINSZ,
};
